FROM python:3.11-slim

WORKDIR /app

#Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

#Copy project files
COPY . .

EXPOSE 8000

# RUN python manage.py collectstatic --noinput
# Run migrations and start server
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]